slam_toolbox:
  ros__parameters:
    # Frame names
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_link"

    # Input topics
    scan_topic: "/scan"
    odom_topic: "/odom"

    # Mode
    mode: "mapping"

    # TF settings
    transform_publish_period: 0.02
    publish_tf: true

    # Map settings
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.5

    # Correlation parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 0.5
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    fine_search_angle_offset: 0.00349

    # Debugging
    use_sim_time: false
    debug: true

