slam_toolbox:
  ros__parameters:
    mode: mapping
    debug_logging: true  # Enable for diagnostics
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    transform_publish_period: 0.02  # 50 Hz
    map_update_interval: 3.0  # Update map every 3 seconds
    minimum_time_interval: 0.5
    resolution: 0.05  # 5 cm/cell
    max_laser_range: 12.0
    transform_tolerance: 0.5
    correlation_search_space_magnification: 1.0
    loop_search_space_magnification: 1.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 0.4
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    fine_search_angle_offset: 0.00349
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 12.0
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    stack_size_to_use: 1000
    enable_interactive_mode: false
